### PR TITLE
Renamed Rect + type coercion (closes #50, #51)

### LINKED ISSUE #50: Generic type enforcement for Rect
We should throw in Rect whenever any of the values are NaN.

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@emtwo ?

**Comment by marcoscaceres** [comment]
@oyiptong r?

**Comment by oyiptong** [comment]
r+

**Comment by oyiptong** [comment]
This PR says that the commit got merged, but I don't see it in https://github.com/mozilla/remote-newtab/commits/gh-pages

weird?

**Comment by marcoscaceres** [comment]
Just for record keeping. We recovered the commit.

**Pull request merged**
