### PR TITLE
Drop JS versions \o/

### PR DESCRIPTION
**Pull request by marcoscaceres**
:notes: _...and I've been waiting for this moment for all my life..._ :notes: (yes I know my life is sad) 

https://www.youtube.com/watch?v=9mNaO7FGaDY

Let there be `let`!

### CODE REVIEW

**Comment by oyiptong** [comment]
yay! when did that happen?

**Comment by sarracini** [comment]
'greatest pull request comment ever' award goes to @marcoscaceres

**Comment by marcoscaceres** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=855665

**Comment by oyiptong** [comment]
r+, but that means we'll need to rebase newtab-dev

**Comment by marcoscaceres** [comment]
It wfm with what's there. Maybe someone else can also confirm?

**Comment by oyiptong** [comment]
Aha. The bug closed today, but the patch landed last week:
https://bugzilla.mozilla.org/show_bug.cgi?id=932517

**Comment by oyiptong** [comment]
nevermind :-)

**Pull request merged**
