### PR TITLE
Revert classic tile look (closes #127)

### LINKED ISSUE #127: remote newtab thumbnails different from non-remote
Thumbnails from remote newtab are different from non-remote:

screen shot 2015-10-31 at 12 21 06 am
screen shot 2015-10-31 at 12 21 10 am

### PR DESCRIPTION
**Pull request by marcoscaceres**
I reverted the CSS, but they still looks lightly different. 

However, the "classic" look is not great, as it's off center.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Adding preview again... failed first time. 

screenshot 2015-11-02 16 37 29

**Comment by marcoscaceres** [comment]
@sarracini r?

**Comment by marcoscaceres** [comment]
@sarracini, the CSS appears to be more or less the same, but if you can see anything I'm missing, please feel free to update the PR.

**Comment by sarracini** [comment]
r+

**Pull request merged**
