### PR TITLE
Cache directory tiles in Service Worker (closes #94)

### LINKED ISSUE #94: Make image caching work for Directory Tiles
Right now, only the user's tiles are offline. It should be possible to also offline the Directory Tiles in the SW.

### PR DESCRIPTION
**Pull request by marcoscaceres**
- renamed mainSiteFiles to mainSiteURLs
- cachetasks.js
  - Now exports itself
  - Add memoizedCaches,
  - Bug fixes! lots of bug fixes. 
  - deleteAllCaches now returns a Map.
- sw.js
  - Gains copyright statement :+1: 
  - initTasks was racy! woops. So they now run one after the other. They now live at `PageThumbTasks.init()`
  -  jscs fixes
  - s\PageThumbTask\PageThumbTasks\g
  - Added `ensureResponse`, which adds a little protection against corrupted content.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@emtwo @sarracini @oyiptong r+?

**Comment by marcoscaceres** [comment]
oops wrong window!

**Comment by marcoscaceres** [comment]
@emtwo @sarracini @oyiptong r+?

**Comment by marcoscaceres** [comment]
@emtwo @sarracini @oyiptong r?

**Comment by oyiptong** [comment]
r+

**Pull request merged**
