### PR TITLE
Fix value on confirmation box

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by oyiptong** [comment]
r+

**Comment by marcoscaceres** [comment]
R-

**Comment by marcoscaceres** [comment]
Actually, @k88hudson fix is correct. r+ from me.

**Comment by marcoscaceres** [comment]
@k88hudson, can you please rebase again... we had to rewrite history on gh-pages :cry: ... we had a rewrite history because we screwed something up.

**Pull request merged**
